language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yanlongsun/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true yanlongsun/docker-react npm run test
